spring:
  application:
    name: course-application
  datasource:
    url: jdbc:postgresql://localhost:5332/maropce
    username: maropce
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    database: postgresql

